config/routes.rb
Lottery::Application.routes.draw do
  
  resources :users

  resources :events

  match 'events/:id/participants' => "events#add_participant", :via => :post, :as => :add_participant
  match 'events/:id/participants' => "events#list_participants", :via => :get, :as => :list_participants
  match 'events/:id/draw' => "events#draw_winner", :via => :post, :as => :draw_winner

  root to: 'static_pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :uid, :name

  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user 

  validates :name, length: { minimum: 2, maximum: 35 }

  def winners
    participations.select { |p| p.won } .map { |p| p.user }
  end

  def non_winning_participations 
    participations.select { |p| !p.won }
  end

  def select_winning_candidate 
    non_winning_participations.sample
  end

  def select_winner_and_save
    winning_participation = select_winning_candidate

    if (winning_participation.nil?) then
      nil
    else
      winning_participation.won = true
      winning_participation.save
      winning_participation.user
   end
  end

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  attr_accessible :event_id, :user_id
  
  belongs_to :event
  belongs_to :user

  validates :event_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email
  
  before_save { |user| user.email = email.downcase }

  has_many :participations, dependent: :destroy
  has_many :events, through: :participations
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def add_participant
    @event = Event.find(params[:id])
    user = User.where("email = ?", params[:email]).first

    if (user.nil?)
      user = User.create(email: params[:email])
    end

    @event.participations.create(user_id: user.id)

    respond_to do |format|
      format.html { redirect_to @event, notice: "Added #{user.email}" } 
    end

  end

  def list_participants
    event = Event.find(params[:id])
    participants = event.participants

    respond_to do |format|
      format.json { render json: participants } 
    end
  end

  def draw_winner
    @event = Event.find(params[:id])

    winner = @event.select_winner_and_save

    respond_to do |format|
      msg =  winner.nil? ? "No one left to draw amongst" : "Congrats to #{winner.email}"
      format.html { redirect_to @event, notice: msg }
    end
  end 

  # GET /events/new
  # GET /events/new.json
  def new
    if flash[:event_params]
      @event = Event.new(flash[:event_params])
      @event.valid?
    else
      @event = Event.new
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end


  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html do
          flash[:error] = "Error creating Event"
          flash[:event_params] = params[:event]
          redirect_to :action => :new 
        end

        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

 
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Lottery"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}" end
	end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="event-index">
  <h1>Lottery Events</h1>

  <% @events.each do |event| %>
    <div>
      <%= link_to event.name, event, { class: "event-name"} %>
      <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <%= link_to 'New Lottery Event', new_event_path, { class: "btn"} %>

</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="event-show" ng-app="event">
	<h1>Lottery Event: <%= @event.name %></h1>

	<div class="section" ng-controller="ParticipantsCtrl">
		<h3>Participants</h3>
		<ul>
			<li ng-repeat="participant in participants">{{participant.email}}</li>
		</ul>
		<form ng-submit="addParticipant()">
			<label for="email">Email:
				<input id="email" type="text" ng-model="emailText" placeholder="Participant's email"></input>
			</label>
			<input type="submit" class="btn" value="Add New Participant">
		</form>
	<div>

	<div class="section">
		<h3>Winners</h3>
		<ul>
			<% @event.winners.each do |winner| %>
				<li> <%= winner.email %> </li>
			<% end %>

			<% if @event.winners.empty? %>
			<p>No winners yet.</p>
			<% end %>
		</ul>

		<form method="post" action="<%= request.fullpath %>/draw">
			<input type="submit" class="btn" value="Pick Next Winner">
		</form>
	<div>


</div>

app/views/layouts/_footer.html.erb
<footer class="footer"> 
	<small>
		Made in Helsinki @ Avaus
  	</small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<header class="navbar navbar-fixed-top clearfix">
			<div class="navbar-inner">
				<div class="container">
					<%= link_to "Avaus Lottery", root_path, { :class=>"brand" } %>
					<nav>
						<ul class="nav pull-right">
							<li><%= link_to "Events", events_path %></li>
							<li><%= link_to "Stats", users_path %></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>

		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>

</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="hero-unit">
<h1>Create a Lottery Event!</h1>
	<p>
		<ol>
			<li>Create your very own lottery 
			<li>Invite people to participate through an email
			<li>Congregate in the same location
			<li>Draw the winners!
		</ol> 
		
		<%= link_to 'Get Started', new_event_path, { class: "btn btn-primary" } %>
	</p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="user-index">

  <h1>Lottery Participants</h1>
   
  <% @users.each do |user| %>
    <div class="user">
      <%= link_to user.email, user, { class: "email" } %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>


  <%= link_to 'New New User', new_user_path, { class: "btn" } %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>